Merged PR 53: feat: support intermediate certificates with customer managed trust
This PR will:
- add the option to configure customer managed issuers with intermediate certificates, not just root certificates by introducing certificate chains
- Add tests for /020_aio_install to be run in the pipeline

Related work items: #497, #513

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -32,7 +32,7 @@ stages:
 
           # Initialize dependency scan and fail the build if it does not pass
           - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
-            displayName: 'Component Detection'
+            displayName: "Component Detection"
             inputs:
               failOnAlert: true
 
@@ -74,7 +74,7 @@ stages:
 
           # Initialize dependency scan and fail the build if it does not pass
           - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
-            displayName: 'Component Detection'
+            displayName: "Component Detection"
             inputs:
               failOnAlert: true
 
@@ -149,7 +149,7 @@ stages:
           - task: AzureCLI@2
             displayName: Azure CLI for Resource Provider Unregistration Script Test
             inputs:
-              azureSubscription: 'azdo-ai-for-edge-iac-for-edge'
+              azureSubscription: "azdo-ai-for-edge-iac-for-edge"
               workingDirectory: "$(System.DefaultWorkingDirectory)/src/000_rp_enablement"
               scriptType: bash
               scriptLocation: inlineScript
@@ -160,7 +160,7 @@ stages:
           - task: AzureCLI@2
             displayName: Azure CLI for Resource Provider Registration Script Test
             inputs:
-              azureSubscription: 'azdo-ai-for-edge-iac-for-edge'
+              azureSubscription: "azdo-ai-for-edge-iac-for-edge"
               workingDirectory: "$(System.DefaultWorkingDirectory)/src/000_rp_enablement"
               scriptType: bash
               scriptLocation: inlineScript
@@ -192,11 +192,12 @@ stages:
             displayName: Check for 010_cluster_install changes
             name: changesInClusterInstallScript
 
-      - job: TerraformTest
+      - job: TerraformClusterTest
         pool:
           vmImage: ubuntu-latest
         dependsOn: CheckTerraformClusterInstallChanges
         condition: eq(dependencies.CheckTerraformClusterInstallChanges.outputs['changesInClusterInstallScript.changesInClusterInstall'], 'true')
+
         steps:
           # Initialize Terraform
           - task: TerraformInstaller@1
@@ -206,53 +207,54 @@ stages:
 
           # Check version and output issue if needed
           - task: TerraformCLI@1
-            displayName: 'Check terraform version'
+            displayName: "Check terraform version"
             inputs:
               command: version
 
           # Run terraform init
           - task: TerraformCLI@1
-            displayName: 'Terraform Init'
+            displayName: "Terraform Init"
             inputs:
               command: init
               workingDirectory: "$(System.DefaultWorkingDirectory)/src/010_cluster_install/terraform/"
               runAzLogin: true
-              environmentServiceName: 'azdo-ai-for-edge-iac-for-edge'
+              environmentServiceName: "azdo-ai-for-edge-iac-for-edge"
               backendType: azurerm
               # Service connection to authorize backend access. Supports Subscription & Management Group Scope
-              backendServiceArm: 'azdo-ai-for-edge-iac-for-edge'
-              backendAzureRmResourceGroupName: 'IaC_For_Edge'
+              backendServiceArm: "azdo-ai-for-edge-iac-for-edge"
+              backendAzureRmResourceGroupName: "IaC_For_Edge"
               # azure location shortname of the backend resource group and storage account
-              backendAzureRmResourceGroupLocation: 'eastus'
-              backendAzureRmStorageAccountName: 'iacforedgetf'
+              backendAzureRmResourceGroupLocation: "eastus"
+              backendAzureRmStorageAccountName: "iacforedgetf"
               # azure blob container to store the state file
-              backendAzureRmContainerName: 'iacforedgetf'
+              backendAzureRmContainerName: "iacforedgetf"
               # azure blob file name
               backendAzureRmKey: infrax.tfstate
 
           - task: TerraformCLI@1
-            displayName: 'Terraform Validate'
+            displayName: "Terraform Validate"
             inputs:
               command: validate
               workingDirectory: "$(System.DefaultWorkingDirectory)/src/010_cluster_install/terraform/"
 
           # Run Terraform Plan for reporting
           - task: TerraformCLI@1
-            displayName: 'Terraform Plan'
+            displayName: "Terraform Plan"
             inputs:
               command: plan
               workingDirectory: "$(System.DefaultWorkingDirectory)/src/010_cluster_install/terraform/"
               runAzLogin: true
-              environmentServiceName: 'azdo-ai-for-edge-iac-for-edge'
-              publishPlanResults: 'Terrafrom Test Plan'
-              commandOptions: '-out=$(Build.ArtifactStagingDirectory)/$(Build.Buildnumber).tfplan
+              environmentServiceName: "azdo-ai-for-edge-iac-for-edge"
+              publishPlanResults: "Terrafrom Test Plan"
+              commandOptions:
+                "-out=$(Build.ArtifactStagingDirectory)/$(Build.Buildnumber).tfplan
                 -detailed-exitcode
                 -var environment=$(TF_VAR_ENVIRONMENT)
                 -var resource_prefix=$(TF_VAR_RESOURCE_PREFIX)
                 -var location=$(TF_VAR_LOCATION)
                 -var existing_resource_group_name=$(TF_VAR_EXISTING_RESOURCE_GROUP_NAME)
                 -var vm_sku_size=$(TF_VAR_VM_SKU_SIZE)
-                -var custom_locations_oid=$(TF_VAR_CUSTOM_LOCATIONS_OID)'
+                -var custom_locations_oid=$(TF_VAR_CUSTOM_LOCATIONS_OID)"
 
           # Terraform Test Command
           # This is not yet implemented, tracking here: https://github.com/jason-johnson/azure-pipelines-tasks-terraform/issues/398
@@ -269,8 +271,133 @@ stages:
           - task: AzureCLI@2
             displayName: Azure CLI for Terraform CLI test run
             inputs:
-              azureSubscription: 'azdo-ai-for-edge-iac-for-edge'
+              azureSubscription: "azdo-ai-for-edge-iac-for-edge"
               workingDirectory: "$(System.DefaultWorkingDirectory)/src/010_cluster_install/terraform"
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                # Export the ARM subscription ID so Terraform tests can be executed
+                export ARM_SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)
+                terraform test -json -var custom_locations_oid=$(TF_VAR_CUSTOM_LOCATIONS_OID) > test_output.log
+                unset ARM_SUBSCRIPTION_ID
+
+                # Define the log file from the test output to read up
+                log_file="test_output.log"
+
+                # Read each line of the log file and extract the @timestamp and @message fields
+                while IFS= read -r line; do
+                  echo "$line" | jq -r '"\(.["@timestamp"]) .... \(.["@message"])"'
+                done < "$log_file"
+
+                # Get the last line of the output and parse it for the word "Success"
+                last_line=$(tail -n 1 test_output.log)
+                if echo "$last_line" | jq -e '.["@message"]' | grep -q "Success"; then
+                  echo "Terraform tests passed."
+                else
+                  echo "Terraform tests failed."
+                  exit 1
+                fi
+
+      - job: CheckTerraformAioInstallChanges
+        displayName: Check for changes in cluster install terraform folder
+        pool:
+          vmImage: ubuntu-latest
+        dependsOn: MegaLinter
+        steps:
+          # Checkout repo
+          - checkout: self
+            fetchDepth: 0
+
+          # Check for changes in the 020_aio_install folder
+          - bash: |
+              echo "Checking for changes in the ./src/020_aio_install folder..."
+              if git diff --name-only @~ @ | grep -qE 'src/020_aio_install/.*\.(tf|tfvars|tfstate|hcl)$'; then
+                echo "Changes detected in the ./src/020_aio_install folder."
+                echo "##vso[task.setvariable variable=changesInAioInstall;isOutput=true]true"
+              else
+                echo "No changes detected in the ./src/020_aio_install folder."
+                echo "##vso[task.setvariable variable=changesInAioInstall;isOutput=true]false"
+              fi
+            displayName: Check for 020_aio_install changes
+            name: changesInAioInstallScript
+
+      - job: TerraformAioTest
+        pool:
+          vmImage: ubuntu-latest
+        dependsOn: CheckTerraformAioInstallChanges
+        condition: eq(dependencies.CheckTerraformAioInstallChanges.outputs['changesInAioInstallScript.changesInAioInstall'], 'true')
+
+        steps:
+          # Initialize Terraform
+          - task: TerraformInstaller@1
+            displayName: install terraform
+            inputs:
+              terraformVersion: latest
+
+          # Check version and output issue if needed
+          - task: TerraformCLI@1
+            displayName: "Check terraform version"
+            inputs:
+              command: version
+
+          # Run terraform init
+          - task: TerraformCLI@1
+            displayName: "Terraform Init"
+            inputs:
+              command: init
+              workingDirectory: "$(System.DefaultWorkingDirectory)/src/020_aio_install/terraform/"
+              runAzLogin: true
+              environmentServiceName: "azdo-ai-for-edge-iac-for-edge"
+              backendType: azurerm
+              # Service connection to authorize backend access. Supports Subscription & Management Group Scope
+              backendServiceArm: "azdo-ai-for-edge-iac-for-edge"
+              backendAzureRmResourceGroupName: "IaC_For_Edge"
+              # azure location shortname of the backend resource group and storage account
+              backendAzureRmResourceGroupLocation: "eastus"
+              backendAzureRmStorageAccountName: "iacforedgetf"
+              # azure blob container to store the state file
+              backendAzureRmContainerName: "iacforedgetf"
+              # azure blob file name
+              backendAzureRmKey: infrax.tfstate
+
+          - task: TerraformCLI@1
+            displayName: "Terraform Validate"
+            inputs:
+              command: validate
+              workingDirectory: "$(System.DefaultWorkingDirectory)/src/020_aio_install/terraform/"
+
+          # Run Terraform Plan for reporting
+          - task: TerraformCLI@1
+            displayName: "Terraform Plan"
+            inputs:
+              command: plan
+              workingDirectory: "$(System.DefaultWorkingDirectory)/src/020_aio_install/terraform/"
+              runAzLogin: true
+              environmentServiceName: "azdo-ai-for-edge-iac-for-edge"
+              publishPlanResults: "Terrafrom Test Plan"
+              commandOptions:
+                "-out=$(Build.ArtifactStagingDirectory)/$(Build.Buildnumber).tfplan
+                -detailed-exitcode
+                -var resource_prefix=$(TF_VAR_RESOURCE_PREFIX)
+                -var location=$(TF_VAR_LOCATION)"
+
+          # Terraform Test Command
+          # This is not yet implemented, tracking here: https://github.com/jason-johnson/azure-pipelines-tasks-terraform/issues/398
+          # Once this command is available, the AZ CLI below can be removed
+          # - task: TerraformCLI@2
+          #   displayName: 'terraform test'
+          #   inputs:
+          #     command: test
+          #     workingDirectory: "$(System.DefaultWorkingDirectory)/src/020_aio_install/terraform/tests"
+          #     commandOptions: "-filter=cluster.tftest.hcl"
+
+          # NOTE: For this task to work it needs the subscription id set for the AzureAD provider
+          # beyond the integrated MSI.
+          - task: AzureCLI@2
+            displayName: Azure CLI for Terraform CLI test run
+            inputs:
+              azureSubscription: "azdo-ai-for-edge-iac-for-edge"
+              workingDirectory: "$(System.DefaultWorkingDirectory)/src/020_aio_install/terraform"
               scriptType: bash
               scriptLocation: inlineScript
               inlineScript: |
